import { useMemo } from "react";
export type McpUiPayload = { type?: "text" | "card" | "table" | "status" | "html"; title?: string; description?: string; status?: "idle" | "running" | "success" | "error"; fields?: Array<{ label: string; value: string }>; rows?: Array<Record<string, string | number | boolean | null>>; html?: string; };
function safe(value: unknown) { if (value == null) return ""; if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") return String(value); try { return JSON.stringify(value); } catch { return ""; } }
/** MCP-style structured result renderer. Raw HTML is never injected into the DOM. */
export function McpUiBlock({ payload }: { payload: McpUiPayload }) {
  const fields = useMemo(() => payload.fields ?? [], [payload.fields]); const rows = useMemo(() => payload.rows ?? [], [payload.rows]);
  const statusLabel = payload.status === "running" ? "กำลังทำงาน" : payload.status === "success" ? "สำเร็จ" : payload.status === "error" ? "ผิดพลาด" : "";
  if (payload.type === "html") return <div className="rounded-xl border border-zinc-800 bg-zinc-950/80 p-3 text-xs text-zinc-300"><div className="mb-2 text-[10px] uppercase tracking-wider text-zinc-500">HTML UI</div><pre className="max-h-72 overflow-auto whitespace-pre-wrap break-words font-mono text-[11px]">{payload.html || ""}</pre></div>;
  return <div className="rounded-xl border border-zinc-800 bg-zinc-950/80 p-3">{(payload.title || statusLabel) && <div className="flex items-center justify-between gap-3"><div className="text-xs font-medium text-zinc-100">{payload.title || "MCP Result"}</div>{statusLabel && <span className="rounded-full border border-zinc-800 px-2 py-0.5 text-[10px] text-zinc-400">{statusLabel}</span>}</div>}{payload.description && <div className="mt-1 text-[11px] leading-5 text-zinc-500">{payload.description}</div>}{fields.length > 0 && <div className="mt-3 grid grid-cols-2 gap-2">{fields.map((field) => <div key={field.label} className="rounded-lg border border-zinc-800/80 bg-zinc-900/70 p-2"><div className="text-[10px] text-zinc-500">{field.label}</div><div className="mt-0.5 truncate text-xs text-zinc-200">{safe(field.value)}</div></div>)}</div>}{rows.length > 0 && <div className="mt-3 overflow-x-auto rounded-lg border border-zinc-800"><table className="w-full text-left text-[11px]"><tbody>{rows.map((row, index) => <tr key={index} className="border-b border-zinc-800 last:border-0">{Object.entries(row).map(([key, value]) => <td key={key} className="px-2 py-1.5 text-zinc-300"><span className="text-zinc-600">{key}: </span>{safe(value)}</td>)}</tr>)}</tbody></table></div>}</div>;
}
